import * as React from "react";
import { Collapsible } from "../../collapsible";
import {
  container,
  titleContainer,
  middleContainer,
} from "../../../css/belief.module.css";

const beliefs = [
  {
    sectionHead: "About God",
    sectionBody:
      "We believe in one God eternally existing in three divine persons: Father, Son, and Holy Spirit. God is the Creator of all things, is perfect in love and holiness, and is worthy of all worship and devotion. He sovereignly rules over all things and brings about his eternal purposes to redeem his lost people and restore his fallen creation.",
  },
  {
    sectionHead: "About Salvation through Jesus Christ",
    sectionBody:
      "We believe that Jesus Christ, being fully God and fully human, was conceived by the Holy Spirit and born of the virgin Mary. He was tempted as we are, but lived a holy life without sin. He died on the cross as an atoning sacrifice to pay for our sin and rebellion, making peace between lost humanity and our holy God through his shed blood. He rose again in victory over death, and ascended to the Father where he intercedes for us and waits to return and make all things new. Through faith in Jesus Christ alone, we are restored to relationship with God and given the gift of eternal life.",
  },
  {
    sectionHead: "About the Work of the Holy Spirit",
    sectionBody:
      "We believe in the person and power of the Holy Spirit, who inspired the holy scriptures, glorifies Jesus Christ, and convicts the world of sin, righteousness, and judgment. It is the work of the Spirit to indwell and regenerate believers, granting adoption and spiritual life. The Holy Spirit continues his work by granting spiritual gifts and sanctifying, instructing, guiding, and empowering believers.",
  },
  {
    sectionHead: "About Revelation",
    sectionBody:
      "We believe that God has revealed himself to the world through the Bible, both Old and New Testaments, which is the only written word of God. The Bible is divinely inspired, authoritative, and without error in all that it affirms, and is the supreme source of truth for faith and living. God also reveals himself through his creation and through the ministry of the Holy Spirit, in alignment with the scriptures.",
  },
  {
    sectionHead: "About Humanity",
    sectionBody:
      "We believe that God created human beings, male and female, in his own image. Humanity is called to multiply and fill the earth as God's image bearers and representatives, to steward the created world, and to live in loving fellowship with God.",
  },
  {
    sectionHead: "About the Fall",
    sectionBody:
      "We believe that our forebears, Adam and Eve, fell into Satan's temptation by disobeying God's command, and were thus separated from fellowship with God and rendered spiritually dead by their sin. As a result, all of humanity is in need of salvation from our sins that can only come by the grace and mercy of God through his Son Jesus Christ.",
  },
  {
    sectionHead: "About the Church",
    sectionBody:
      "We believe that the Church is the bride of Christ who he shed his blood to save, and is made up of all people who through saving faith in Jesus have been regenerated by the Holy Spirit and are united together as Christ's body. Jesus is the head of his universal Church, which is manifested in local churches. The Church together lives out Christ's commands and pursues his mission in the world.",
  },
  {
    sectionHead: "About the New Creation",
    sectionBody:
      "We believe in the visible, personal, glorious, imminent return of Jesus Christ, His bodily resurrection of the dead, the judgment of the just and the unjust, and the fulfillment of Christ's Kingdom in the new heavens and the new earth. Then shall the eager expectation of creation be fulfilled and the whole earth shall proclaim the glory of God who makes all things new.",
  },
];

const Belief = () => (
  <div className={container}>
    <div className={titleContainer}>
      <div className="subheading">Our Beliefs</div>
      <h2>What We Believe</h2>
    </div>
    <div className={middleContainer}>
      <div className="flex flex-col gap-y-10 pb-10">
        {beliefs
          .filter((_, index) => index < beliefs.length / 2)
          .map((beliefs, index) => (
            <Collapsible
              key={index}
              sectionHead={beliefs.sectionHead}
              sectionBody={beliefs.sectionBody}
            />
          ))}
      </div>
      <div className="flex flex-col gap-y-10">
        {beliefs
          .filter((_, index) => index >= beliefs.length / 2)
          .map((beliefs, index) => (
            <Collapsible
              key={index}
              sectionHead={beliefs.sectionHead}
              sectionBody={beliefs.sectionBody}
            />
          ))}
      </div>
    </div>
  </div>
);
export default Belief;
