FROM node:18-alpine

# Needed for arm64 architectures
RUN apk add --no-cache make gcc g++ python3 curl

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /opt/frontend/
COPY package.json ./
RUN npm install
ENV PATH /opt/frontend/node_modules/.bin:$PATH

COPY . .
RUN chown -R node:node /opt/frontend
USER node
RUN gatsby telemetry --disable
EXPOSE 8000
CMD ["sh", "./scripts/wait-for-strapi.sh", "npm", "run", "develop"]
