version: "3"
services:
  gatsby:
    container_name: gatsby
    build:
      context: ./frontend/
      dockerfile: Dockerfile-FullBuildFrontend
    image: hmccaa/hmcc-web:gatsby-0.1.1a
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./frontend/src/:/opt/frontend/src/
    networks:
      - strapi
    depends_on:
      - strapi
  strapi:
    container_name: strapi
    env_file: ./cms/.env
    build:
      context: ./cms/
      dockerfile: Dockerfile-FullBuildCms
    image: hmccaa/hmcc-web:strapi-0.1.1a
    restart: unless-stopped
    environment:
      DATABASE_HOST: strapiDB
    ports:
      - "1337:1337"
    volumes:
      - ./cms/src/:/opt/cms/src/
    networks:
      - strapi
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: ./cms/.env
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - strapi-data:/var/lib/mysql
      #- ./data:/var/lib/mysql # if you want to use a bind folder
    ports:
      - "3306:3306"
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
