name: Validate Frontend
inputs: 
  strapi_token:
    type: string
    required: true
  strapi_server:
    type: string
    required: true
  host_server:
    type: string
    required: true
runs:
  using: "composite"
  steps:
    - name: Build Gatsby
      shell: bash
      run: |
        cd ${{ github.workspace }}/frontend

        # Add env file
        echo 'STRAPI_TOKEN=${{ inputs.strapi_token }}' > ./.env.production
        echo 'STRAPI_API_URL=${{ inputs.strapi_server }}' >> ./.env.production

        npm install
        NODE_ENV=production HOST_ORIGIN=${{ inputs.host_server }} npm run build
