name: Component - Validate Frontend
on:
  workflow_call:
    inputs:
      concurrency_group:
        required: true
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ inputs.concurrency_group }}
      cancel-in-progress: true
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Build Gatsby
        run: |
          cd ${{ github.workspace }}/frontend

          # Add env file
          echo 'STRAPI_TOKEN=${{ secrets.STRAPI_TOKEN }}' > ./.env.production
          echo 'STRAPI_API_URL=${{ secrets.STRAPI_SERVER }}' >> ./.env.production

          npm install
          NODE_ENV=production npm run build
