name: Publish Production Frontend
run-name: Deploy New Release to Production (triggered by ${{ github.actor }})
on:
  push:
    branches:
      - "release"
  workflow_dispatch:
    
jobs:
  deploy-prod-site:
    uses: ./.github/workflows/component-deploy-prod.yml
    secrets: inherit