name: Publish Production Frontend
run-name: Deploy after PR merge to release branch (merged by ${{ github.actor }})
on:
  push:
    branches:
      - "release"
  workflow_dispatch:
    
jobs:
  deploy-prod-site:
    uses: ./.github/workflows/workflow-deploy-prod.yml
