name: Validate Release Build
run-name: Validate Release Build (${{ github.actor }})
on:
  pull_request:
    branches:
      - "release"
jobs:
  validate-prod-frontend:
    runs-on: ubuntu-latest
    concurrency:
      group: validate-dev-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Validate Frontend
        uses: ./.github/actions/validate-frontend
        with:
          strapi_token: ${{ secrets.STRAPI_TOKEN }}
          strapi_server: ${{ secrets.STRAPI_SERVER }}