name: Validate Release Build
run-name: Validate Release Build (${{ github.actor }})
on:
  pull_request:
    branches:
      - "release"
jobs:
  validate-prod-frontend:
    uses: ./.github/workflows/component-validate-frontend.yml
    with:
      concurrency_group: validate-prod-${{ github.ref }}
    secrets: inherit